
include		../../rules/Makefile.top

MolPE-VERSION	= 1.1
KMODS		= MolPE
MolPE-OBJS	= MolPE.o MolCPU.o MolPIC.o MolNVRAM.o ../common/$(ODIR)/libcommon.a		  
include		$(rules)/Rules.osx
include		$(rules)/Rules.make

